### ISSUE TITLE
Empty/Null value 

### ISSUE THREAD

**Issue by ikymasie** [adorsys/sms-parser-android#8]
hi,

Im using Twilio and i cant seem to read the incoming message because there is no END_MESSAGE tag... its simple "your code is:" <BEGIN ... and the code... 

Please help

**Comment by luckyhandler** [comment]
Please specify the problem a bit more. Are you using this library?

**Comment by luckyhandler** [comment]
@ikymasie Without any more details this ticket will be closed soon.
