### ISSUE TITLE
Format Number

### ISSUE THREAD

**Issue by KostyaLyapochkin** [adorsys/sms-parser-android#9]
Hello! I have a problem with your library. Please me help. 
https://stackoverflow.com/questions/51215810/android-sdk-parsing-sms?noredirect=1#comment89413669_51215810

**Comment by drilonrecica** [comment]
Hi @KostyaLyapochkin,

We will look into this and inform you about our findings.

Thanks for using the sms parser library.

**Comment by KostyaLyapochkin** [comment]
Thanks @drilonreqica !
I will be wait answer. I need this library =)

**Comment by luckyhandler** [comment]
@KostyaLyapochkin I tried to reproduce the issue with the exact same prerequisites as you and could not find any bug. See my stackoverflow answer for more info. For now I close this issue.
